### ISSUE TITLE
怎么添加istoreOS首页

### ISSUE THREAD

**Issue by yndzm** [oppen321/OpenWrt-24.10#1]
这样行吗

git clone https://github.com/linkease/nas-packages package/new/nas-packages
git clone https://github.com/linkease/nas-packages-luci package/new/nas-packages-luci

**Comment by oppen321** [comment]
增加istore的quickstart插件

**Comment by oppen321** [comment]
在diy-script.sh中加入git clone --depth=1 -b main https://github.com/linkease/nas-packages-luci package/nas-packages-luci

**Comment by oppen321** [comment]
可以的

**Comment by yndzm** [comment]
报错，编译失败，WARNING: Makefile 'package/nas-packages-luci/luci/luci-app-ddnsto/Makefile' has a dependency on 'ddnsto', which does not exist
WARNING: Makefile 'package/nas-packages-luci/luci/luci-app-floatip/Makefile' has a dependency on 'floatip', which does not exist
WARNING: Makefile 'package/nas-packages-luci/luci/luci-app-istoreenhance/Makefile' has a dependency on 'istoreenhance', which does not exist
WARNING: Makefile 'package/nas-packages-luci/luci/luci-app-linkease/Makefile' has a dependency on 'linkease', which does not exist
WARNING: Makefile 'package/nas-packages-luci/luci/luci-app-quickstart/Makefile' has a dependency on 'quickstart', which does not exist
WARNING: Makefile 'package/nas-packages-luci/luci/luci-app-unishare/Makefile' has a dependency on 'unishare', which does not exist

**Comment by yndzm** [comment]
make[2]: *** [package/Makefile:99: package/install] Error 255
make[2]: Leaving directory '/home/runner/work/24.10-6.6/24.10-6.6/openwrt'
make[1]: *** [package/Makefile:174: /home/runner/work/24.10-6.6/24.10-6.6/openwrt/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/runner/work/24.10-6.6/24.10-6.6/openwrt'
make: *** [/home/runner/work/24.10-6.6/24.10-6.6/openwrt/include/toplevel.mk:248: world] Error 2
Error: Process completed with exit code 2.
