### ISSUE TITLE
lucky怎么换成原作者的源

### ISSUE THREAD

**Issue by yndzm** [oppen321/OpenWrt-24.10#2]

**Comment by oppen321** [comment]
在diy-script.sh中加入
git clone  https://github.com/gdy666/luci-app-lucky.git package/lucky
在config中加入luci-app-lucky

**Comment by oppen321** [comment]
想要fock本项目执行action动作需要修改worker中的secrets.TOKEN_OPPEN321将tocken换成你自己的

**Comment by yndzm** [comment]
具体怎么更换tocken

**Comment by oppen321** [comment]
google一下有这方面的教程的

**Comment by oppen321** [comment]
另外由于正在优化ZeroWrt选项菜单所以现在编译会报错，等我修复

**Comment by yndzm** [comment]
OK

**Comment by yndzm** [comment]
![Uploading Screenshot_2024-12-15-18-06-37-949_mark.via.jpg…]()

**Comment by yndzm** [comment]
![Uploading Screenshot_2024-12-15-18-07-13-246_mark.via-edit.jpg…]()

**Comment by yndzm** [comment]
是不是图中选项

**Comment by oppen321** [comment]
麻烦重新上传图片我这里看不到你上传的图片
