### ISSUE TITLE
quickstart 编译成功，使用中老是死机，查看编译过程如下

### ISSUE THREAD

**Issue by yndzm** [oppen321/OpenWrt-24.10#3]
_luci-app-quickstart_ does not support JavaScript source minification
luci-app-quickstart does not support CSS source minification
luci-app-quickstart does not support JavaScript source minification
luci-app-quickstart does not support CSS source minification

**Comment by oppen321** [comment]
暂时不要加入，看的是未正确支持压缩和缺少相关依赖
